### ISSUE TITLE
COPYJOB doesn't work 

### ISSUE THREAD

**Issue by AstaDusquise** [BugisoftRSG/SCAPI#3]
Everytime i try to use it i get           

                                                                                                                                                                
?xml version="1.0" encoding="utf-8"?>
Response xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="CreateContent">
  Status0/Status
  Error Code="AuthenticationFailed" CodeEx="Ticket" />
/Response>

My GTA V is open and i did try with other thing like createticket "Auth -> Invalid credentials or rate limited" i am 100% sure it's the correct mail password and profile name still nothing

**Comment by BugisoftRSG** [comment]
Maybe they have updated the offset for the ticket, gotta check later

**Comment by AstaDusquise** [comment]
Ok thanks and for the createticket is it normal that it's doesn't work it's keep giving me Auth -> Invalid credentials or rate limited i try with 3 account of mine that have gta v and it's keep giving me the error and everything is correct ?

**Comment by BugisoftRSG** [comment]
Rockstar's Security Team changed the way how CreateTicketSc3 works so... its no longer possible to create a ticket with this. There are some workarounds like getting the launcher ticket and so on like fivem does but it has no high priority for you.

**Comment by BugisoftRSG** [comment]
Should be now fix with the latest commit

**Comment by AstaDusquise** [comment]
Same error git clone the repo and build it again same thing 
![image](https://github.com/BugisoftRSG/SCAPI/assets/146788943/9eb51e26-f72f-4086-98b1-7f6f407d7839)

**Comment by AstaDusquise** [comment]
and is there another way to talk with you ?

**Comment by BugisoftRSG** [comment]
discord: bugisoft.meta

**Comment by BugisoftRSG** [comment]
At the start the console should say like: TICKET = ..., etc. is it empty?
