### ISSUE TITLE
Auth keeps retuning " Invalid credentials " even if they are correct

### ISSUE THREAD

**Issue by ghost** [BugisoftRSG/SCAPI#4]
Hello,

I'm experiencing issues with the program. Whenever I enter my credentials, the authentication fails with the message " Auth -> Invalid credentials or rate limited. "

I'm unsure if I'm making a mistake or if the API has undergone significant changes.

Thank you for your assistance !

![Screenshot 2024-06-24 222723](https://github.com/BugisoftRSG/SCAPI/assets/144916167/e84b6e00-51af-4c27-8e7f-f976d8565eab)

EDIT : Inserted the screenshot correctly.

**Comment by BugisoftRSG** [comment]
Hi, this program is not designed to be used by end users as-is. Anyway the offsets at [here](https://github.com/BugisoftRSG/SCAPI/blob/c59829b7a073aae4c8b5378da13c4d65ebeb96e8/src/main.cpp#L105) needs to be updated.

**Comment by ghost** [comment]
Hi, thank you for your answer.

I'm sorry but I don't understand what " end user " mean.

Also, I forgot to mention that I disabled the part of the code where it uses the game to retrieve tickets and stuff.

EDIT : Oh alright I got it now, sorry for the issue.
